spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/serg-maximchuk/microservices-demo
          searchPaths: config

  security:
    user:
      name: user
      password: pass

server:
  port: 9090
